spring:
  application:
    name: PixShift
  data:
    mongodb:
      username: mongo
      password: mongo
      host: localhost
      port: 27017
      database: pixshift
      authentication-database: admin
  cloud:
    azure:
      storage:
        blob:
          account-name: ${AZURE_ACCOUNT_NAME}
          account-key: ${AZURE_ACCOUNT_KEY}
          endpoint: ${AZURE_STORAGE_ENDPOINT}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
